namespace Kuvik.ONDC.Api.Services.Transaction;
public enum TransactionState { SearchInitiated, SearchReceived, SelectInitiated, SelectReceived, ConfirmInitiated, ConfirmReceived, StatusRequested, StatusReceived, Failed }
public sealed class OndcTransaction { public string TransactionId { get; set; } = ""; public string MessageId { get; set; } = ""; public string Action { get; set; } = ""; public TransactionState State { get; set; } public string? ProviderId { get; set; } public string? ItemId { get; set; } public string? ApplicationReference { get; set; } public string PayloadJson { get; set; } = ""; public string? ErrorCode { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } }
public interface ITransactionRepository { Task<OndcTransaction?> GetAsync(string transactionId, CancellationToken ct); Task AddAsync(OndcTransaction transaction, CancellationToken ct); Task SaveAsync(CancellationToken ct); }
public sealed class TransactionRepository(Data.OndcDbContext db) : ITransactionRepository { public Task<OndcTransaction?> GetAsync(string id, CancellationToken ct) => db.Transactions.FindAsync([id], ct).AsTask(); public Task AddAsync(OndcTransaction tx, CancellationToken ct) => db.Transactions.AddAsync(tx, ct).AsTask(); public Task SaveAsync(CancellationToken ct) => db.SaveChangesAsync(ct); }
public interface ITransactionService { Task RecordAsync(Models.Common.OndcEnvelope envelope, TransactionState target, CancellationToken ct); Task EnsureForActionAsync(Models.Common.OndcEnvelope envelope, string action, CancellationToken ct); }
public sealed class TransactionService(ITransactionRepository repo) : ITransactionService { static readonly Dictionary<TransactionState, TransactionState[]> Allowed = new() { [TransactionState.SearchInitiated]=[TransactionState.SearchReceived,TransactionState.Failed], [TransactionState.SearchReceived]=[TransactionState.SelectInitiated,TransactionState.Failed], [TransactionState.SelectInitiated]=[TransactionState.SelectReceived,TransactionState.Failed], [TransactionState.SelectReceived]=[TransactionState.ConfirmInitiated,TransactionState.Failed], [TransactionState.ConfirmInitiated]=[TransactionState.ConfirmReceived,TransactionState.Failed], [TransactionState.ConfirmReceived]=[TransactionState.StatusRequested,TransactionState.Failed], [TransactionState.StatusRequested]=[TransactionState.StatusReceived,TransactionState.Failed] };
 public async Task RecordAsync(Models.Common.OndcEnvelope e, TransactionState target, CancellationToken ct) { var tx=await repo.GetAsync(e.Context.TransactionId,ct); if(tx is null){ await repo.AddAsync(new OndcTransaction { TransactionId=e.Context.TransactionId,MessageId=e.Context.MessageId,Action=e.Context.Action,State=target,PayloadJson=e.Message.GetRawText(),CreatedAt=DateTimeOffset.UtcNow,UpdatedAt=DateTimeOffset.UtcNow },ct); } else { if(!Allowed.TryGetValue(tx.State,out var next)||!next.Contains(target)) throw new InvalidOperationException($"Invalid transaction transition {tx.State} -> {target}."); tx.State=target; tx.MessageId=e.Context.MessageId; tx.Action=e.Context.Action; tx.PayloadJson=e.Message.GetRawText(); tx.UpdatedAt=DateTimeOffset.UtcNow; } await repo.SaveAsync(ct); }
 public async Task EnsureForActionAsync(Models.Common.OndcEnvelope e,string action,CancellationToken ct) { var tx=await repo.GetAsync(e.Context.TransactionId,ct) ?? throw new KeyNotFoundException("ONDC transaction was not found."); var required=action switch { "select"=>TransactionState.SearchReceived,"confirm"=>TransactionState.SelectReceived,"status"=>TransactionState.ConfirmReceived,_=>throw new ArgumentOutOfRangeException(nameof(action)) }; if(tx.State!=required) throw new InvalidOperationException($"Action '{action}' requires state {required}; current state is {tx.State}."); } }
