using System.Collections.Concurrent;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Kuvik.ONDC.Api.Configuration;
using Microsoft.Extensions.Options;
using Org.BouncyCastle.Crypto.Digests;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Crypto.Signers;
namespace Kuvik.ONDC.Api.Services.Signature;
public interface ILocalMockKeyStore { string BapPrivateKey { get; } string BapKeyId { get; } string BppPrivateKey { get; } string BppKeyId { get; } string BppPublicKey { get; } string BapPublicKey { get; } }
public sealed class LocalMockKeyStore : ILocalMockKeyStore { readonly byte[] bap=RandomNumberGenerator.GetBytes(32), bpp=RandomNumberGenerator.GetBytes(32); public string BapPrivateKey => Convert.ToBase64String(bap); public string BapKeyId => "local-bap-key"; public string BppPrivateKey => Convert.ToBase64String(bpp); public string BppKeyId => "local-bpp-key"; public string BppPublicKey => Convert.ToBase64String(new Ed25519PrivateKeyParameters(bpp,0).GeneratePublicKey().GetEncoded()); public string BapPublicKey => Convert.ToBase64String(new Ed25519PrivateKeyParameters(bap,0).GeneratePublicKey().GetEncoded()); }
public interface ISubscriberKeyResolver { string? Resolve(string subscriberId, string keyId); }
public sealed class ConfigurationSubscriberKeyResolver(IOptions<OndcOptions> options, ILocalMockKeyStore mockKeys) : ISubscriberKeyResolver { public string? Resolve(string subscriberId,string keyId) { var o=options.Value; if(o.TrustedSubscriberKeys.TryGetValue($"{subscriberId}|{keyId}",out var key)) return key; if(!o.LocalMock.Enabled) return null; if(subscriberId==o.LocalMock.BppId && keyId==mockKeys.BppKeyId) return mockKeys.BppPublicKey; if(subscriberId==o.SubscriberId) { if(!String.IsNullOrWhiteSpace(o.SigningPrivateKey)) { var raw=Convert.FromBase64String(o.SigningPrivateKey); return Convert.ToBase64String(new Ed25519PrivateKeyParameters(raw.AsSpan(0,32).ToArray(),0).GeneratePublicKey().GetEncoded()); } if(keyId==mockKeys.BapKeyId) return mockKeys.BapPublicKey; } return null; } }
public interface IOndcSignatureService { string CreateAuthorization(string rawBody); string CreateMockAuthorization(string rawBody); void Verify(string rawBody,string? header); }
public sealed class OndcSignatureService(IOptions<OndcOptions> options, ISubscriberKeyResolver keyResolver, ILocalMockKeyStore mockKeys) : IOndcSignatureService {
 private static readonly Regex Pair = new("(?<k>[A-Za-z]+)=\\\"(?<v>[^\\\"]+)\\\"",RegexOptions.Compiled); private readonly ConcurrentDictionary<string,long> replay = new();
 public string CreateAuthorization(string body) { var o=options.Value; if(o.LocalMock.Enabled) return Create(body,o.SubscriberId,mockKeys.BapKeyId,mockKeys.BapPrivateKey); if(String.IsNullOrWhiteSpace(o.SigningPrivateKey)||String.IsNullOrWhiteSpace(o.SigningKeyId)) throw new InvalidOperationException("ONDC signing credentials are not configured."); return Create(body,o.SubscriberId,o.SigningKeyId,o.SigningPrivateKey); }
 public string CreateMockAuthorization(string body) { var o=options.Value; if(!o.LocalMock.Enabled) throw new InvalidOperationException("Local mock is disabled."); return Create(body,o.LocalMock.BppId,mockKeys.BppKeyId,mockKeys.BppPrivateKey); }
 string Create(string body,string subscriberId,string keyId,string privateKey) { var created=DateTimeOffset.UtcNow.ToUnixTimeSeconds(); var expires=created+300; var data=Encoding.UTF8.GetBytes(SigningString(body,created,expires)); var raw=Convert.FromBase64String(privateKey); if(raw.Length is not (32 or 64)) throw new InvalidOperationException("ONDC signing private key must be a base64 Ed25519 seed or private key."); var signer=new Ed25519Signer(); signer.Init(true,new Ed25519PrivateKeyParameters(raw.AsSpan(0,32).ToArray(),0)); signer.BlockUpdate(data,0,data.Length); var signature=Convert.ToBase64String(signer.GenerateSignature()); return $"Signature keyId=\"{subscriberId}|{keyId}|ed25519\",algorithm=\"ed25519\",created=\"{created}\",expires=\"{expires}\",headers=\"(created) (expires) digest\",signature=\"{signature}\""; }
 public void Verify(string body,string? header) { if(String.IsNullOrWhiteSpace(header)||!header.StartsWith("Signature ",StringComparison.Ordinal)) throw new UnauthorizedAccessException("Missing ONDC Authorization signature."); var p=Pair.Matches(header).ToDictionary(m=>m.Groups["k"].Value,m=>m.Groups["v"].Value,StringComparer.OrdinalIgnoreCase); if(!p.TryGetValue("keyId",out var keyId)||!p.TryGetValue("algorithm",out var algorithm)||!p.TryGetValue("created",out var createdText)||!p.TryGetValue("expires",out var expiresText)||!p.TryGetValue("signature",out var sigText)||algorithm!="ed25519") throw new UnauthorizedAccessException("Malformed ONDC signature."); var parts=keyId.Split('|'); if(parts.Length!=3||parts[2]!="ed25519"||!long.TryParse(createdText,out var created)||!long.TryParse(expiresText,out var expires)) throw new UnauthorizedAccessException("Invalid ONDC signature metadata."); var now=DateTimeOffset.UtcNow.ToUnixTimeSeconds(); if(created>now+60||expires<now||expires-created>600) throw new UnauthorizedAccessException("Expired or invalid ONDC signature window."); if(!replay.TryAdd(sigText,expires)) throw new UnauthorizedAccessException("Replayed ONDC signature."); foreach(var old in replay.Where(x=>x.Value<now).Select(x=>x.Key)) replay.TryRemove(old,out _); var key=keyResolver.Resolve(parts[0],parts[1]) ?? throw new UnauthorizedAccessException("No trusted ONDC public key is available for sender."); try { var verifier=new Ed25519Signer(); verifier.Init(false,new Ed25519PublicKeyParameters(Convert.FromBase64String(key),0)); var bytes=Encoding.UTF8.GetBytes(SigningString(body,created,expires)); verifier.BlockUpdate(bytes,0,bytes.Length); if(!verifier.VerifySignature(Convert.FromBase64String(sigText))) throw new UnauthorizedAccessException("Invalid ONDC signature."); } catch(FormatException) { throw new UnauthorizedAccessException("Invalid ONDC signature encoding."); } }
 static string SigningString(string body,long created,long expires) => $"(created): {created}\\n(expires): {expires}\\ndigest: BLAKE-512={Digest(body)}";
 static string Digest(string body) { var d=new Blake2bDigest(512); var b=Encoding.UTF8.GetBytes(body); d.BlockUpdate(b,0,b.Length); var output=new byte[64]; d.DoFinal(output,0); return Convert.ToBase64String(output); }
}
